// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Person
	HelloRequest
	HelloResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Language int32

const (
	Language_ENGLISH  Language = 0
	Language_JAPANESE Language = 1
)

var Language_name = map[int32]string{
	0: "ENGLISH",
	1: "JAPANESE",
}
var Language_value = map[string]int32{
	"ENGLISH":  0,
	"JAPANESE": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}
func (Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Person struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type HelloRequest struct {
	You      *Person   `protobuf:"bytes,1,opt,name=you" json:"you,omitempty"`
	Theirs   []*Person `protobuf:"bytes,2,rep,name=theirs" json:"theirs,omitempty"`
	Language Language  `protobuf:"varint,3,opt,name=language,enum=api.Language" json:"language,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloRequest) GetYou() *Person {
	if m != nil {
		return m.You
	}
	return nil
}

func (m *HelloRequest) GetTheirs() []*Person {
	if m != nil {
		return m.Theirs
	}
	return nil
}

func (m *HelloRequest) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_ENGLISH
}

type HelloResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "api.Person")
	proto.RegisterType((*HelloRequest)(nil), "api.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "api.HelloResponse")
	proto.RegisterEnum("api.Language", Language_name, Language_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/api.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4d, 0x6b, 0x83, 0x40,
	0x10, 0x86, 0x63, 0x04, 0x3f, 0xc6, 0xa4, 0xa4, 0x73, 0x92, 0x96, 0x80, 0x58, 0x0a, 0x49, 0x0f,
	0x39, 0x98, 0x7b, 0x21, 0x50, 0x49, 0x5a, 0x82, 0x04, 0xfd, 0x01, 0x65, 0x0b, 0xd3, 0x54, 0x50,
	0xd7, 0xee, 0xae, 0x87, 0x1c, 0xfa, 0xdf, 0xcb, 0xae, 0x5a, 0x42, 0x8f, 0xfb, 0x3c, 0xb3, 0xef,
	0xbb, 0xb3, 0xe0, 0xb3, 0xb6, 0xdc, 0xb4, 0x82, 0x2b, 0x8e, 0x36, 0x6b, 0xcb, 0xf8, 0x05, 0x9c,
	0x13, 0x09, 0xc9, 0x1b, 0x5c, 0x02, 0x7c, 0x96, 0x42, 0xaa, 0xf7, 0x86, 0xd5, 0x14, 0x5a, 0x91,
	0xb5, 0xf2, 0x73, 0xdf, 0x90, 0x8c, 0xd5, 0x84, 0xf7, 0xe0, 0x57, 0x6c, 0xb4, 0x53, 0x63, 0x3d,
	0x0d, 0xb4, 0x8c, 0x7f, 0x60, 0x76, 0xa0, 0xaa, 0xe2, 0x39, 0x7d, 0x77, 0x24, 0x15, 0x2e, 0xc1,
	0xbe, 0xf0, 0xce, 0x84, 0x04, 0x49, 0xb0, 0xd1, 0x9d, 0x7d, 0x4b, 0xae, 0x39, 0x3e, 0x80, 0xa3,
	0xbe, 0xa8, 0x14, 0x32, 0x9c, 0x46, 0xf6, 0xff, 0x89, 0x41, 0xe1, 0x1a, 0xbc, 0x8a, 0x35, 0xe7,
	0x8e, 0x9d, 0x29, 0xb4, 0x23, 0x6b, 0x75, 0x93, 0xcc, 0xcd, 0xd8, 0x71, 0x80, 0xf9, 0x9f, 0x8e,
	0xd7, 0x30, 0x1f, 0xea, 0x65, 0xcb, 0x1b, 0x49, 0x18, 0x82, 0x5b, 0x93, 0x94, 0xfa, 0x6a, 0xbf,
	0xc8, 0x78, 0x7c, 0x7a, 0x04, 0x6f, 0x0c, 0xc0, 0x00, 0xdc, 0x34, 0xdb, 0x1f, 0x5f, 0x8b, 0xc3,
	0x62, 0x82, 0x33, 0xf0, 0xde, 0x76, 0xa7, 0x5d, 0x96, 0x16, 0xe9, 0xc2, 0x4a, 0x9e, 0xc1, 0xdd,
	0x0b, 0x22, 0x45, 0x02, 0xb7, 0xe0, 0x15, 0xec, 0x62, 0xf2, 0xf1, 0xd6, 0xbc, 0xe0, 0x7a, 0xd5,
	0x3b, 0xbc, 0x46, 0x7d, 0x7d, 0x3c, 0xf9, 0x70, 0xcc, 0x17, 0x6f, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0xce, 0x6a, 0x1d, 0x6f, 0x01, 0x00, 0x00,
}
