// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Language int32

const (
	Language_ENGLISH  Language = 0
	Language_JAPANESE Language = 1
)

var Language_name = map[int32]string{
	0: "ENGLISH",
	1: "JAPANESE",
}
var Language_value = map[string]int32{
	"ENGLISH":  0,
	"JAPANESE": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}
func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{0}
}

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
	Gender_OTHER  Gender = 2
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}
var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{1}
}

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender               Gender   `protobuf:"varint,3,opt,name=gender,proto3,enum=api.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

type CreateUsersRequest struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUsersRequest) Reset()         { *m = CreateUsersRequest{} }
func (m *CreateUsersRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUsersRequest) ProtoMessage()    {}
func (*CreateUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{1}
}
func (m *CreateUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUsersRequest.Unmarshal(m, b)
}
func (m *CreateUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUsersRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUsersRequest.Merge(dst, src)
}
func (m *CreateUsersRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUsersRequest.Size(m)
}
func (m *CreateUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUsersRequest proto.InternalMessageInfo

func (m *CreateUsersRequest) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateUsersResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUsersResponse) Reset()         { *m = CreateUsersResponse{} }
func (m *CreateUsersResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUsersResponse) ProtoMessage()    {}
func (*CreateUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{2}
}
func (m *CreateUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUsersResponse.Unmarshal(m, b)
}
func (m *CreateUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUsersResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUsersResponse.Merge(dst, src)
}
func (m *CreateUsersResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUsersResponse.Size(m)
}
func (m *CreateUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUsersResponse proto.InternalMessageInfo

func (m *CreateUsersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{3}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	Users                []*ListUsersResponse_User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{4}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*ListUsersResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListUsersResponse_User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse_User) Reset()         { *m = ListUsersResponse_User{} }
func (m *ListUsersResponse_User) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse_User) ProtoMessage()    {}
func (*ListUsersResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{4, 0}
}
func (m *ListUsersResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse_User.Unmarshal(m, b)
}
func (m *ListUsersResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse_User.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse_User.Merge(dst, src)
}
func (m *ListUsersResponse_User) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse_User.Size(m)
}
func (m *ListUsersResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse_User proto.InternalMessageInfo

func (m *ListUsersResponse_User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListUsersResponse_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{5}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_f18aad3b72ffdd06, []int{6}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*CreateUsersRequest)(nil), "api.CreateUsersRequest")
	proto.RegisterType((*CreateUsersResponse)(nil), "api.CreateUsersResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "api.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "api.ListUsersResponse")
	proto.RegisterType((*ListUsersResponse_User)(nil), "api.ListUsersResponse.User")
	proto.RegisterType((*GetUserRequest)(nil), "api.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "api.GetUserResponse")
	proto.RegisterEnum("api.Language", Language_name, Language_value)
	proto.RegisterEnum("api.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUsers(ctx context.Context, in *CreateUsersRequest, opts ...grpc.CallOption) (*CreateUsersResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUsers(ctx context.Context, in *CreateUsersRequest, opts ...grpc.CallOption) (*CreateUsersResponse, error) {
	out := new(CreateUsersResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/CreateUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUsers(context.Context, *CreateUsersRequest) (*CreateUsersResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/CreateUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUsers(ctx, req.(*CreateUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUsers",
			Handler:    _UserService_CreateUsers_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_f18aad3b72ffdd06) }

var fileDescriptor_api_f18aad3b72ffdd06 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4f, 0xa3, 0x40,
	0x14, 0xc5, 0x81, 0x52, 0x0a, 0x97, 0x4d, 0x97, 0xbd, 0xdd, 0x3f, 0xa4, 0x4d, 0xb3, 0x64, 0x36,
	0x9b, 0x74, 0xfb, 0xd0, 0xd5, 0x1a, 0x7d, 0xf2, 0xa5, 0x1a, 0x6c, 0x35, 0x58, 0x0d, 0xd5, 0x67,
	0x33, 0xda, 0x91, 0x90, 0x58, 0x8a, 0x0c, 0xf5, 0x2b, 0xfa, 0xb5, 0x0c, 0x03, 0x34, 0xd0, 0xfa,
	0x36, 0x73, 0xee, 0x3d, 0x73, 0xee, 0xfc, 0x66, 0xc0, 0xa0, 0x71, 0x38, 0x8a, 0x93, 0x75, 0xba,
	0xc6, 0x06, 0x8d, 0x43, 0x12, 0x80, 0x7a, 0xcf, 0x59, 0x82, 0x7d, 0x80, 0xe7, 0x30, 0xe1, 0xe9,
	0x43, 0x44, 0x57, 0xcc, 0x96, 0x1d, 0x79, 0x60, 0xf8, 0x86, 0x50, 0xe6, 0x74, 0xc5, 0xb0, 0x07,
	0xc6, 0x0b, 0x2d, 0xab, 0x8a, 0xa8, 0xea, 0x99, 0x20, 0x8a, 0x7f, 0x40, 0x0b, 0x58, 0xb4, 0x64,
	0x89, 0xdd, 0x70, 0xe4, 0x41, 0x7b, 0x6c, 0x8e, 0xb2, 0x90, 0xa9, 0x90, 0xfc, 0xa2, 0x44, 0x8e,
	0x01, 0xcf, 0x13, 0x46, 0x53, 0x96, 0xc5, 0x71, 0x9f, 0xbd, 0x6e, 0x18, 0x4f, 0xf1, 0x37, 0x34,
	0x37, 0xd9, 0xde, 0x96, 0x9d, 0xc6, 0xc0, 0x1c, 0x1b, 0xc2, 0x99, 0x75, 0xf8, 0xb9, 0x4e, 0xfe,
	0x43, 0xa7, 0x66, 0xe3, 0xf1, 0x3a, 0xe2, 0x0c, 0x6d, 0x68, 0xad, 0x18, 0xe7, 0x34, 0x28, 0x67,
	0x2d, 0xb7, 0x04, 0xc1, 0xf2, 0x42, 0x9e, 0x56, 0x53, 0x48, 0x02, 0xdf, 0x2a, 0x5a, 0x71, 0xc4,
	0x61, 0x3d, 0xba, 0x27, 0xa2, 0xf7, 0xda, 0xaa, 0xc3, 0x74, 0x87, 0x05, 0xac, 0x36, 0x28, 0xe1,
	0xb2, 0x08, 0x56, 0xc2, 0x25, 0x22, 0xa8, 0x15, 0x30, 0x62, 0x4d, 0x1c, 0x68, 0x4f, 0x99, 0x38,
	0xab, 0xbc, 0xeb, 0x8e, 0x8b, 0x1c, 0xc0, 0xd7, 0x6d, 0x47, 0x31, 0x53, 0x1f, 0xd4, 0x2c, 0x49,
	0x34, 0xd5, 0x68, 0x08, 0x79, 0xf8, 0x17, 0x74, 0x8f, 0x46, 0xc1, 0x86, 0x06, 0x0c, 0x4d, 0x68,
	0xb9, 0xf3, 0xa9, 0x77, 0xb9, 0x98, 0x59, 0x12, 0x7e, 0x01, 0xfd, 0x6a, 0x72, 0x3b, 0x99, 0xbb,
	0x0b, 0xd7, 0x92, 0x87, 0xff, 0x40, 0xcb, 0xe1, 0xa3, 0x0e, 0xea, 0xf5, 0xc4, 0x73, 0x2d, 0x09,
	0x01, 0xb4, 0x0b, 0x57, 0xac, 0x65, 0x34, 0xa0, 0x79, 0x73, 0x37, 0x73, 0x7d, 0x4b, 0x19, 0xbf,
	0xcb, 0x60, 0x66, 0x01, 0x0b, 0x96, 0xbc, 0x85, 0x4f, 0x0c, 0xcf, 0xc0, 0xac, 0xe0, 0xc6, 0x5f,
	0x62, 0x82, 0xfd, 0x77, 0xeb, 0xda, 0xfb, 0x85, 0xfc, 0x0a, 0x44, 0xc2, 0x53, 0x30, 0xb6, 0x18,
	0xf1, 0xc7, 0x2e, 0xd6, 0xdc, 0xff, 0xf3, 0x73, 0xda, 0x44, 0xc2, 0x13, 0x68, 0x15, 0x54, 0xb0,
	0x53, 0xfc, 0xa3, 0x2a, 0xc5, 0xee, 0xf7, 0xba, 0x58, 0xfa, 0x1e, 0x35, 0xf1, 0xa9, 0x8f, 0x3e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0x35, 0x14, 0x2a, 0xe1, 0x02, 0x00, 0x00,
}
