// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	User
	RegisterUsersRequest
	RegisterUsersResponse
	ListUsersRequest
	ListUsersResponse
	GetUserRequest
	GetUserResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Language int32

const (
	Language_ENGLISH  Language = 0
	Language_JAPANESE Language = 1
)

var Language_name = map[int32]string{
	0: "ENGLISH",
	1: "JAPANESE",
}
var Language_value = map[string]int32{
	"ENGLISH":  0,
	"JAPANESE": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}
func (Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
	Gender_OTHER  Gender = 2
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}
var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type User struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Gender    Gender `protobuf:"varint,3,opt,name=gender,enum=api.Gender" json:"gender,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

type RegisterUsersRequest struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *RegisterUsersRequest) Reset()                    { *m = RegisterUsersRequest{} }
func (m *RegisterUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUsersRequest) ProtoMessage()               {}
func (*RegisterUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterUsersRequest) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type RegisterUsersResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RegisterUsersResponse) Reset()                    { *m = RegisterUsersResponse{} }
func (m *RegisterUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterUsersResponse) ProtoMessage()               {}
func (*RegisterUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterUsersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListUsersRequest struct {
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListUsersResponse struct {
	Users []*ListUsersResponse_User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersResponse) Reset()                    { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()               {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListUsersResponse) GetUsers() []*ListUsersResponse_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListUsersResponse_User struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ListUsersResponse_User) Reset()                    { *m = ListUsersResponse_User{} }
func (m *ListUsersResponse_User) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse_User) ProtoMessage()               {}
func (*ListUsersResponse_User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *ListUsersResponse_User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListUsersResponse_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*RegisterUsersRequest)(nil), "api.RegisterUsersRequest")
	proto.RegisterType((*RegisterUsersResponse)(nil), "api.RegisterUsersResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "api.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "api.ListUsersResponse")
	proto.RegisterType((*ListUsersResponse_User)(nil), "api.ListUsersResponse.User")
	proto.RegisterType((*GetUserRequest)(nil), "api.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "api.GetUserResponse")
	proto.RegisterEnum("api.Language", Language_name, Language_value)
	proto.RegisterEnum("api.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HumanService service

type HumanServiceClient interface {
	RegisterUsers(ctx context.Context, in *RegisterUsersRequest, opts ...grpc.CallOption) (*RegisterUsersResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type humanServiceClient struct {
	cc *grpc.ClientConn
}

func NewHumanServiceClient(cc *grpc.ClientConn) HumanServiceClient {
	return &humanServiceClient{cc}
}

func (c *humanServiceClient) RegisterUsers(ctx context.Context, in *RegisterUsersRequest, opts ...grpc.CallOption) (*RegisterUsersResponse, error) {
	out := new(RegisterUsersResponse)
	err := grpc.Invoke(ctx, "/api.HumanService/RegisterUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := grpc.Invoke(ctx, "/api.HumanService/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/api.HumanService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HumanService service

type HumanServiceServer interface {
	RegisterUsers(context.Context, *RegisterUsersRequest) (*RegisterUsersResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterHumanServiceServer(s *grpc.Server, srv HumanServiceServer) {
	s.RegisterService(&_HumanService_serviceDesc, srv)
}

func _HumanService_RegisterUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).RegisterUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HumanService/RegisterUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).RegisterUsers(ctx, req.(*RegisterUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HumanService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HumanService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HumanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HumanService",
	HandlerType: (*HumanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUsers",
			Handler:    _HumanService_RegisterUsers_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _HumanService_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _HumanService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x51, 0xef, 0x93, 0x30,
	0x14, 0xc5, 0x81, 0x31, 0x06, 0x77, 0x7f, 0x27, 0x5e, 0x37, 0x83, 0x2c, 0x8b, 0xa4, 0xc6, 0x64,
	0xee, 0x61, 0x71, 0x33, 0xd1, 0x17, 0x5f, 0xf6, 0x80, 0x43, 0x83, 0xd3, 0x30, 0x7d, 0x36, 0xd5,
	0x55, 0xd2, 0x44, 0x18, 0x52, 0xf0, 0x63, 0xfa, 0x99, 0x0c, 0x05, 0x16, 0xd8, 0x7f, 0x6f, 0xed,
	0x39, 0xf7, 0xf6, 0xdc, 0xfe, 0x5a, 0xb0, 0x68, 0xc6, 0xd7, 0x59, 0x7e, 0x2e, 0xce, 0x38, 0xa0,
	0x19, 0x27, 0x31, 0xe8, 0xdf, 0x04, 0xcb, 0x71, 0x01, 0xf0, 0x8b, 0xe7, 0xa2, 0xf8, 0x9e, 0xd2,
	0x84, 0x39, 0xaa, 0xa7, 0x2e, 0xad, 0xc8, 0x92, 0xca, 0x81, 0x26, 0x0c, 0xe7, 0x60, 0xfd, 0xa6,
	0xad, 0xab, 0x49, 0xd7, 0xac, 0x04, 0x69, 0x3e, 0x07, 0x23, 0x66, 0xe9, 0x89, 0xe5, 0xce, 0xc0,
	0x53, 0x97, 0x93, 0xed, 0x78, 0x5d, 0x85, 0xec, 0xa5, 0x14, 0x35, 0x16, 0x79, 0x0b, 0xd3, 0x88,
	0xc5, 0x5c, 0x14, 0x2c, 0xaf, 0x02, 0x45, 0xc4, 0xfe, 0x94, 0x4c, 0x14, 0xf8, 0x0c, 0x86, 0x65,
	0xb5, 0x77, 0x54, 0x6f, 0xb0, 0x1c, 0x6f, 0x2d, 0xd9, 0x5b, 0x55, 0x44, 0xb5, 0x4e, 0x36, 0x30,
	0xbb, 0x6a, 0x14, 0xd9, 0x39, 0x15, 0x0c, 0x1d, 0x18, 0x25, 0x4c, 0x08, 0x1a, 0xb7, 0xf3, 0xb6,
	0x5b, 0x82, 0x60, 0x87, 0x5c, 0x14, 0xdd, 0x1c, 0x92, 0xc3, 0xa3, 0x8e, 0xd6, 0x1c, 0xb1, 0xe9,
	0x87, 0xcf, 0x65, 0xf8, 0xbd, 0xb2, 0xee, 0x38, 0xee, 0xaa, 0x01, 0x36, 0x01, 0x8d, 0x9f, 0x64,
	0xf0, 0x30, 0xd2, 0xf8, 0x09, 0x11, 0xf4, 0x0e, 0x1c, 0xb9, 0x26, 0x1e, 0x4c, 0xf6, 0x4c, 0x9e,
	0xd5, 0xde, 0xf6, 0xaa, 0x8b, 0xbc, 0x82, 0x87, 0x97, 0x8a, 0x66, 0xa6, 0x05, 0xe8, 0x55, 0x92,
	0x2c, 0xea, 0xf1, 0x90, 0xf2, 0xea, 0x05, 0x98, 0x21, 0x4d, 0xe3, 0x92, 0xc6, 0x0c, 0xc7, 0x30,
	0xf2, 0x0f, 0xfb, 0xf0, 0xc3, 0x31, 0xb0, 0x15, 0xbc, 0x03, 0xf3, 0xe3, 0xee, 0xcb, 0xee, 0xe0,
	0x1f, 0x7d, 0x5b, 0x5d, 0xbd, 0x04, 0xa3, 0x7e, 0x00, 0x34, 0x41, 0xff, 0xb4, 0x0b, 0x7d, 0x5b,
	0x41, 0x00, 0xe3, 0xbd, 0x2f, 0xd7, 0x2a, 0x5a, 0x30, 0xfc, 0xfc, 0x35, 0xf0, 0x23, 0x5b, 0xdb,
	0xfe, 0x53, 0xe1, 0x2e, 0x28, 0x13, 0x9a, 0x1e, 0x59, 0xfe, 0x97, 0xff, 0x64, 0x18, 0xc0, 0x83,
	0x1e, 0x71, 0x7c, 0x2a, 0x87, 0xb8, 0xf5, 0x7c, 0xae, 0x7b, 0xcb, 0xaa, 0x6f, 0x42, 0x14, 0x7c,
	0x07, 0xd6, 0x85, 0x26, 0xce, 0xae, 0xe9, 0xd6, 0x27, 0x3c, 0xb9, 0x0d, 0x9d, 0x28, 0xf8, 0x06,
	0x46, 0x0d, 0x1c, 0x7c, 0xdc, 0x7c, 0xa9, 0x2e, 0x4c, 0x77, 0xda, 0x17, 0xdb, 0xbe, 0x1f, 0x86,
	0xfc, 0xdf, 0xaf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x3d, 0x89, 0x13, 0xec, 0x02, 0x00,
	0x00,
}
